# Generated by Django 2.2.12 on 2021-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210706_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='new title', max_length=200),
            preserve_default=False,
        ),
    ]
