# Generated by Django 2.2.12 on 2021-07-11 02:46

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210711_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=248, null=True, validators=[blog.validators.validate_author_email, blog.validators.validate_kiran]),
        ),
    ]
