# Generated by Django 2.2.12 on 2021-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique, please try something else '}, help_text='must be a unique title', max_length=200, unique=True, verbose_name='Post Title'),
        ),
    ]
